// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3wl-ru-ehpkCx7IKoLpLiL2hnjEx0PNA',
    appId: '1:1055813663291:web:bb6b9bfbdfc8b5bdd53a1e',
    messagingSenderId: '1055813663291',
    projectId: 'darkhwastai',
    authDomain: 'darkhwastai.firebaseapp.com',
    storageBucket: 'darkhwastai.firebasestorage.app',
    measurementId: 'G-3YL9FRSSWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuuzenoxSkPT7iWuZkM3BjwPKOcvsS2RM',
    appId: '1:1055813663291:android:4677cbfc5444b480d53a1e',
    messagingSenderId: '1055813663291',
    projectId: 'darkhwastai',
    storageBucket: 'darkhwastai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHdikHPMKua0vXNVKAyKC9R4PWgGwA2s',
    appId: '1:1055813663291:ios:b5fa459e3ab297ded53a1e',
    messagingSenderId: '1055813663291',
    projectId: 'darkhwastai',
    storageBucket: 'darkhwastai.firebasestorage.app',
    iosBundleId: 'com.example.darkhwastAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHdikHPMKua0vXNVKAyKC9R4PWgGwA2s',
    appId: '1:1055813663291:ios:b5fa459e3ab297ded53a1e',
    messagingSenderId: '1055813663291',
    projectId: 'darkhwastai',
    storageBucket: 'darkhwastai.firebasestorage.app',
    iosBundleId: 'com.example.darkhwastAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3wl-ru-ehpkCx7IKoLpLiL2hnjEx0PNA',
    appId: '1:1055813663291:web:233ad9f9889f45d9d53a1e',
    messagingSenderId: '1055813663291',
    projectId: 'darkhwastai',
    authDomain: 'darkhwastai.firebaseapp.com',
    storageBucket: 'darkhwastai.firebasestorage.app',
    measurementId: 'G-KS0JD522N5',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC3wl-ru-ehpkCx7IKoLpLiL2hnjEx0PNA',
    appId: '1:1055813663291:web:5a3e8ed3f027d1a0d53a1e',
    messagingSenderId: '1055813663291',
    projectId: 'darkhwastai',
    authDomain: 'darkhwastai.firebaseapp.com',
    storageBucket: 'darkhwastai.firebasestorage.app',
    measurementId: 'G-WSRXDD6B9F',
  );
}
